Z010D: Update from latest stock version WW 8916-13.8.26.110

diff --git a/Z010D/proprietary/bin/BackupCalibrationData b/Z010D/proprietary/bin/BackupCalibrationData
--- a/Z010D/proprietary/bin/BackupCalibrationData
+++ b/Z010D/proprietary/bin/BackupCalibrationData
@@ -1,15 +1,12 @@
 #!/system/bin/sh
 
-DATADATA="/data/data/"
-GC2155_GOLDEN="/gc2155_golden.txt"
-GC2155_RESPONSE="/gc2155_response.txt"
-GC2155_SHADING="/gc2155_shading.txt"
+DATADATA="/data/.tmp/"
+T4K37F_GOLDEN="/t4k37f_golden.txt"
+T4K37F_RESPONSE="/t4k37f_response.txt"
+T4K37F_SHADING="/t4k37f_shading.txt"
 OV5670_GOLDEN="/ov5670_golden.txt"
 OV5670_RESPONSE="/ov5670_response.txt"
 OV5670_SHADING="/ov5670_shading.txt"
-IMX219_GOLDEN="/imx219_golden.txt"
-IMX219_RESPONSE="/imx219_response.txt"
-IMX219_SHADING="/imx219_shading.txt"
 T4K35_GOLDEN="/t4k35_golden.txt"
 T4K35_RESPONSE="/t4k35_response.txt"
 T4K35_SHADING="/t4k35_shading.txt"
@@ -19,6 +16,12 @@ T4K37_SHADING="/t4k37_shading.txt"
 MN34150_GOLDEN="/mn34150_golden.txt"
 MN34150_RESPONSE="/mn34150_response.txt"
 MN34150_SHADING="/mn34150_shading.txt"
+OV5670_GT_GOLDEN="/ov5670_gt_golden.txt"
+OV5670_GT_RESPONSE="/ov5670_gt_response.txt"
+OV5670_GT_SHADING="/ov5670_gt_shading.txt"
+MN34150_GS_GOLDEN="/mn34150_gs_golden.txt"
+MN34150_GS_RESPONSE="/mn34150_gs_response.txt"
+MN34150_GS_SHADING="/mn34150_gs_shading.txt"
 
 VCM_MACRO="/vcm_macro.txt"
 VCM_MACRO_CAL="/vcm_macro_H.txt"
@@ -26,10 +29,141 @@ VCM_30CM="/vcm_30cm.txt"
 VCM_50CM="/vcm_50cm.txt"
 VCM_INF="/vcm_inf.txt"
 VCM_INF_CAL="/vcm_inf_H.txt"
+
+VCM_MACRO_FRONT="/vcm_macro_V_front.txt"
+VCM_30CM_FRONT="/vcm_30cm_front.txt"
+VCM_50CM_FRONT="/vcm_50cm_front.txt"
+VCM_INF_FRONT="/vcm_inf_V_front.txt"
+
 FACTORY_FOLDER="/factory"
 DEBUG=0
+PULL_VCM=0
 
-fail()
+function rear_lens() {
+	OTP=`CameraOTP 0`
+	moduleID=${OTP:41:4}
+	if [ $DEBUG -eq 1 ]; then
+		echo $moduleID
+	fi
+	case $moduleID in
+		"0x24")
+			if [ $DEBUG -eq 1 ]; then
+				echo MN34150_LA
+			fi
+				REAR_GOLDEN=$MN34150_GOLDEN
+				REAR_RESPONSE=$MN34150_RESPONSE
+				REAR_SHADING=$MN34150_SHADING
+		;;
+		"0x33")
+			if [ $DEBUG -eq 1 ]; then
+				echo MN34150_GS
+			fi
+				REAR_GOLDEN=$MN34150_GS_GOLDEN
+				REAR_RESPONSE=$MN34150_GS_RESPONSE
+				REAR_SHADING=$MN34150_GS_SHADING
+		;;
+		*)
+			echo WRONG MODULE
+		;;
+	esac
+}
+
+function rear_sensor_quality() {
+
+	ID=`cat /proc/driver/RearModule`
+	case $ID in
+		"T4K37")
+			if [ $DEBUG -eq 1 ]; then
+				echo T4K37
+			fi
+			REAR_GOLDEN=$T4K37_GOLDEN
+			REAR_RESPONSE=$T4K37_RESPONSE
+			REAR_SHADING=$T4K37_SHADING
+			PULL_VCM=1
+		;;
+		"T4K35")
+			if [ $DEBUG -eq 1 ]; then
+				echo T4K35
+			fi
+			REAR_GOLDEN=$T4K35_GOLDEN
+			REAR_RESPONSE=$T4K35_RESPONSE
+			REAR_SHADING=$T4K35_SHADING
+			PULL_VCM=1
+		;;
+		"MN34150")
+			rear_lens
+			PULL_VCM=1		
+		;;
+		*)
+		echo "Incredible! No Sensor."
+		;;
+	esac
+}
+
+function front_lens() {
+
+	OTP=`CameraOTP 1`
+	moduleID=${OTP:41:4}
+	if [ $DEBUG -eq 1 ]; then
+		echo $moduleID
+	fi
+	case $moduleID in
+		"0x11")
+			if [ $DEBUG -eq 1 ]; then
+				echo DS
+			fi
+			FRONT_GOLDEN=$OV5670_GOLDEN
+			FRONT_RESPONSE=$OV5670_RESPONSE
+			FRONT_SHADING=$OV5670_SHADING
+
+		;;
+		"0x23")
+			if [ $DEBUG -eq 1 ]; then
+				echo GT
+			fi
+			FRONT_GOLDEN=$OV5670_GT_GOLDEN
+			FRONT_RESPONSE=$OV5670_GT_RESPONSE
+			FRONT_SHADING=$OV5670_GT_SHADING
+
+		;;
+		*)
+			echo WRONG MODULE		
+		;;
+	esac
+}
+
+function front_sensor_quality() {
+
+	ID=`cat /proc/driver/FrontModule`
+	case $ID in
+		"OV5670")
+			front_lens
+			PULL_VCM=0
+		;;
+		"T4K37F")
+			if [ $DEBUG -eq 1 ]; then
+				echo T4K37F
+			fi
+			FRONT_GOLDEN=$T4K37F_GOLDEN
+			FRONT_RESPONSE=$T4K37F_RESPONSE
+			FRONT_SHADING=$T4K37F_SHADING
+			PULL_VCM=1
+		;;
+		"GC2155")
+			if [ $DEBUG -eq 1 ]; then
+				echo GC2155
+			fi
+			FRONT_GOLDEN=$GC2155_GOLDEN
+			FRONT_RESPONSE=$GC2155_RESPONSE
+			FRONT_SHADING=$GC2155_SHADING
+			PULL_VCM=0
+		;;
+		*)
+		echo "Incredible! No Sensor."
+		;;
+	esac
+}
+function fail()
 {
   if [ $DEBUG -eq 1 ]; then
     echo "FAIL: wrong input Parameter"
@@ -39,7 +173,7 @@ fail()
   exit 0
 }
 
-copyfile()
+function copyfile()
 {
 
   if [ -e $FACTORY_FOLDER$1 ]; then
@@ -56,141 +190,89 @@ copyfile()
 
 }
 
-CopyRearCameraOTPData()
+function CopyRearCameraOTPData()
 {
     if [ ! -d $DATADATA$1 ]; then
       mkdir "$DATADATA$1"
     fi
-	ID=`cat /proc/driver/RearModule`
-	case $ID in
-		"T4K37") 
-			#T4K37
-		    copyfile $T4K37_GOLDEN $1
-			if [ $? -ne 0 ]; then
-				return 1
-			fi
-			copyfile $T4K37_RESPONSE $1
-			if [ $? -ne 0 ]; then
-				return 1
-			fi
-			copyfile $T4K37_SHADING $1
-			if [ $? -ne 0 ]; then
-				return 1
-			fi
-		;;
-		"T4K35")
-			#T4K35
-		    copyfile $T4K35_GOLDEN $1
-			if [ $? -ne 0 ]; then
-				return 1
-			fi
-			copyfile $T4K35_RESPONSE $1
-			if [ $? -ne 0 ]; then
-				return 1
-			fi
-			copyfile $T4K35_SHADING $1
-			if [ $? -ne 0 ]; then
-				return 1
-			fi
-		;;
-		"IMX219")
-			#IMX219
-		    copyfile $IMX219_GOLDEN $1
-			if [ $? -ne 0 ]; then
-				return 1
-			fi
-			copyfile $IMX219_RESPONSE $1
-			if [ $? -ne 0 ]; then
-				return 1
-			fi
-			copyfile $IMX219_SHADING $1
-			if [ $? -ne 0 ]; then
-				return 1
-			fi
-		;;
-		"MN34150")
-			#MN34150
-		    copyfile $MN34150_GOLDEN $1
-			if [ $? -ne 0 ]; then
-				return 1
-			fi
-			copyfile $MN34150_RESPONSE $1
-			if [ $? -ne 0 ]; then
-				return 1
-			fi
-			copyfile $MN34150_SHADING $1
-			if [ $? -ne 0 ]; then
-				return 1
-			fi
-		;;
-		*)
-		echo "Incredible! No Sensor."
-		;;
-	esac
+
+	copyfile $REAR_GOLDEN $1
+	if [ $? -ne 0 ]; then
+		return 1
+	fi
+	copyfile $REAR_RESPONSE $1
+	if [ $? -ne 0 ]; then
+		return 1
+	fi
+	copyfile $REAR_SHADING $1
+	if [ $? -ne 0 ]; then
+		return 1
+	fi
+	
 	copyfile $VCM_MACRO $1
+	if [ $? -ne 0 ]; then
+		return 1
+	fi
 	copyfile $VCM_MACRO_CAL $1
     copyfile $VCM_30CM $1
 	copyfile $VCM_50CM $1
     copyfile $VCM_INF $1
+	if [ $? -ne 0 ]; then
+		return 1
+	fi
 	copyfile $VCM_INF_CAL $1
-
+	if [ $? -ne 0 ]; then
+		return 1
+	fi
+	
     return 0
 }
 
 
-CopyFrontCameraOTPData()
+function CopyFrontCameraOTPData()
 {
     if [ ! -d $DATADATA$1 ]; then
       mkdir "$DATADATA$1"
     fi
-	ID=`cat /proc/driver/FrontModule`
-	case $ID in
-		"OV5670")
-			#OV5670
-			copyfile $OV5670_GOLDEN $1
-			if [ $? -ne 0 ]; then
-				return 1
-			fi
-			copyfile $OV5670_RESPONSE $1
-			if [ $? -ne 0 ]; then
-				  return 1
-			fi
-			copyfile $OV5670_SHADING $1
-			if [ $? -ne 0 ]; then
-				return 1
-			fi
-			return 0 
-		;;
-		"GC2155")
-			#GC2155
-			copyfile $GC2155_GOLDEN $1
-			if [ $? -ne 0 ]; then
-				return 1
-			fi
-			copyfile $GC2155_RESPONSE $1
-			if [ $? -ne 0 ]; then
-				  return 1
-			fi
-			copyfile $GC2155_SHADING $1
-			if [ $? -ne 0 ]; then
-				return 1
-			fi
-			return 0 
-		;;
-		*)
-		echo "Incredible! No Sensor."
-		;;
-	esac   
+	
+	copyfile $FRONT_GOLDEN $1
+	if [ $? -ne 0 ]; then
+		return 1
+	fi
+	copyfile $FRONT_RESPONSE $1
+	if [ $? -ne 0 ]; then
+		return 1
+	fi
+	copyfile $FRONT_SHADING $1
+	if [ $? -ne 0 ]; then
+		return 1
+	fi	
+
+	if [ $PULL_VCM -eq 1 ]; then
+		#echo "Not AF module, don't pull AF calibration data"
+	#else
+		copyfile $VCM_30CM_FRONT $1
+		copyfile $VCM_50CM_FRONT $1
+		copyfile $VCM_MACRO_FRONT $1
+		if [ $? -ne 0 ]; then
+			return 1
+		fi
+		copyfile $VCM_INF_FRONT $1
+		if [ $? -ne 0 ]; then
+			return 1
+		fi
+	fi
+	
     return 0
 }
 
-TarOTPData()
+function TarOTPData()
 {
-    cd $DATADATA && busybox tar -zcf "$1.tar.gz" $1
+    cd $DATADATA && cameratoolbxs tar -zcf "$1.tar.gz" $1
 
   if [ ! -e "$DATADATA$1.tar.gz" ]; then
     if [ $DEBUG -eq 1 ]; then
-      echo FAIL: "$DATADATA$1.tar.gz" dors not generate.
+      echo FAIL: "$DATADATA$1.tar.gz" does not generate.
     fi
     return 1
   fi
@@ -205,23 +287,25 @@ fi
 
 case "$1" in
   "0")
-        CopyRearCameraOTPData $2
-	if [ $? -eq 0 ]; then
-	  TarOTPData $2
-	  if [ $? -eq 0 ]; then
-    	    echo "PASS"
-	  else
-    	    echo "FAIL"
-	    exit 0
-	  fi
-	else
-    	  echo "FAIL"
-	  exit 0
-	fi
-        exit 0
+	rear_sensor_quality
+        CopyRearCameraOTPData $2	
+		if [ $? -eq 0 ]; then
+		  TarOTPData $2
+		  if [ $? -eq 0 ]; then
+				echo "PASS"
+		  else
+				echo "FAIL"
+			exit 0
+		  fi
+		else
+			  echo "FAIL"
+		  exit 0
+		fi
+			exit 0
    ;;
 
   "1")		
+	front_sensor_quality
 	CopyFrontCameraOTPData $2
 	if [ $? -eq 0 ]; then
 	  TarOTPData $2
@@ -243,4 +327,4 @@ case "$1" in
     fail
     ;;
 
-esac    
+esac
